#!/usr/bin/env bash

export SPOTIFY_CLIENT_ID="SPOTIFY_CLIENT_ID"
export SPOTIFY_CLIENT_SECRET="SPOTIFY_CLIENT_SECRET"
export SPOTIFY_REDIRECT_URI="SPOTIFY_REDIRECT_URI"
export OPENAI_API_KEY="OPENAI_API_KEY"
